[{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 14,
	"startColumn": 15,
	"endLineNumber": 14,
	"endColumn": 18,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 14,
	"startColumn": 20,
	"endLineNumber": 14,
	"endColumn": 23,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 26,
	"startColumn": 40,
	"endLineNumber": 26,
	"endColumn": 43,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 26,
	"startColumn": 45,
	"endLineNumber": 26,
	"endColumn": 48,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'lugar' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 51,
	"startColumn": 58,
	"endLineNumber": 51,
	"endColumn": 63,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'lugar' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 58,
	"startColumn": 54,
	"endLineNumber": 58,
	"endColumn": 59,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'index' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 58,
	"startColumn": 61,
	"endLineNumber": 58,
	"endColumn": 66,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 100,
	"startColumn": 18,
	"endLineNumber": 100,
	"endColumn": 21,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 100,
	"startColumn": 23,
	"endLineNumber": 100,
	"endColumn": 26,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7034",
	"severity": 8,
	"message": "Variable 'wholeData' implicitly has type 'any[]' in some locations where its type cannot be determined.",
	"source": "ts",
	"startLineNumber": 102,
	"startColumn": 7,
	"endLineNumber": 102,
	"endColumn": 16,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'snapshot' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 104,
	"startColumn": 11,
	"endLineNumber": 104,
	"endColumn": 19,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'doc' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 105,
	"startColumn": 24,
	"endLineNumber": 105,
	"endColumn": 27,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7005",
	"severity": 8,
	"message": "Variable 'wholeData' implicitly has an 'any[]' type.",
	"source": "ts",
	"startLineNumber": 106,
	"startColumn": 16,
	"endLineNumber": 106,
	"endColumn": 25,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'error' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 108,
	"startColumn": 12,
	"endLineNumber": 108,
	"endColumn": 17,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 111,
	"startColumn": 20,
	"endLineNumber": 111,
	"endColumn": 23,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 111,
	"startColumn": 25,
	"endLineNumber": 111,
	"endColumn": 28,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7034",
	"severity": 8,
	"message": "Variable 'wholeData' implicitly has type 'any[]' in some locations where its type cannot be determined.",
	"source": "ts",
	"startLineNumber": 113,
	"startColumn": 7,
	"endLineNumber": 113,
	"endColumn": 16,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'snapshot' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 115,
	"startColumn": 11,
	"endLineNumber": 115,
	"endColumn": 19,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'doc' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 116,
	"startColumn": 24,
	"endLineNumber": 116,
	"endColumn": 27,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7005",
	"severity": 8,
	"message": "Variable 'wholeData' implicitly has an 'any[]' type.",
	"source": "ts",
	"startLineNumber": 117,
	"startColumn": 16,
	"endLineNumber": 117,
	"endColumn": 25,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'error' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 119,
	"startColumn": 12,
	"endLineNumber": 119,
	"endColumn": 17,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 122,
	"startColumn": 22,
	"endLineNumber": 122,
	"endColumn": 25,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 122,
	"startColumn": 27,
	"endLineNumber": 122,
	"endColumn": 30,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7034",
	"severity": 8,
	"message": "Variable 'wholeData' implicitly has type 'any[]' in some locations where its type cannot be determined.",
	"source": "ts",
	"startLineNumber": 124,
	"startColumn": 7,
	"endLineNumber": 124,
	"endColumn": 16,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'snapshot' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 126,
	"startColumn": 11,
	"endLineNumber": 126,
	"endColumn": 19,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'doc' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 127,
	"startColumn": 24,
	"endLineNumber": 127,
	"endColumn": 27,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7005",
	"severity": 8,
	"message": "Variable 'wholeData' implicitly has an 'any[]' type.",
	"source": "ts",
	"startLineNumber": 128,
	"startColumn": 16,
	"endLineNumber": 128,
	"endColumn": 25,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'error' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 130,
	"startColumn": 12,
	"endLineNumber": 130,
	"endColumn": 17,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'req' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 133,
	"startColumn": 24,
	"endLineNumber": 133,
	"endColumn": 27,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'res' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 133,
	"startColumn": 29,
	"endLineNumber": 133,
	"endColumn": 32,
	"modelVersionId": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/maide/Desktop/arva-app/app/(tabs)/economia.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'error' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 144,
	"startColumn": 10,
	"endLineNumber": 144,
	"endColumn": 15,
	"modelVersionId": 54,
	"origin": "extHost1"
}]